### ISSUE TITLE
create README

### ISSUE THREAD

**Issue by aakzsh** [aakzsh/gta-done#1]
create a readme file

**Comment by adam-weiler** [comment]
Hey, could I be assigned to this? What details do you need to be included in the readme file?

**Comment by aakzsh** [comment]
[here](https://github.com/aakzsh/gta-done/blob/master/README.md)

**Comment by aakzsh** [comment]
Yes thanks!

**Comment by aakzsh** [comment]
#9 should've fixed the issue, hence closing it now!
